### ISSUE TITLE
Following the readme tutorial, errorFieldName: Currency

### ISSUE THREAD

**Issue by mathieumagalhaes** [worldline/sips-sdk-nodejs#1]
Following the tutorial (simulation user) I'm seeing the following error:
`InitializationResponse { responseCode: 12, errorFieldName: 'currency' }`

Code used:
```
const Dom = require('sips-payment-dom');
const SDK = require('sips-payment-sdk');

const Environment = Dom.Environment;
const PaymentRequest = Dom.PaymentRequest;
const Currency = Dom.Currency;
const OrderChannel = Dom.OrderChannel;
const PaypageClient = SDK.PaypageClient;

const paypageClient = new PaypageClient(
  Environment.SIMU,
  '002001000000002',
  1,                          // This shouldn't be hardcoded here...
  '002001000000002_KEY1',     // ...and neither should this.
);

process.env.NODE_ENV = 'development';

const paymentRequest = new PaymentRequest();
paymentRequest.amount = 1;
paymentRequest.currency = paymentRequest.currencyCode = parseInt(Currency.EUR);
paymentRequest.orderChannel = OrderChannel.INTERNET;
paymentRequest.transactionReference = 'TestTransactionDevelopment-' + new Date().getTime();

const initializationResponse = paypageClient.initializePayment(paymentRequest);

const test = async () => {
  console.log(await initializationResponse);
}

test();
```

**Comment by CrlH** [comment]
You're adding an unknown field `currency` to the request:
```javascript
paymentRequest.currency = paymentRequest.currencyCode = parseInt(Currency.EUR);
```
Try changing it to:

```javascript
const paymentRequest = new PaymentRequest();
paymentRequest.amount = 1;
paymentRequest.currencyCode = Currency.EUR;
paymentRequest.orderChannel = OrderChannel.INTERNET;
paymentRequest.transactionReference = 'TestTransactionDevelopment-' + new Date().getTime();
```

Also, no need to `parseInt`, that will be handled for you! 😉

**Comment by mathieumagalhaes** [comment]
@CrlH Yes indeed, was confused as Documentation we received from Worldline describes using "currencyCode" and the Readme on this Git describes using "currency".

The parseInt was a remaining test case to see if that would solve anything.
We were successful using your example (shortening the transactionReference as it was too long as well). Thank you.

But looking further in this git's code we see there is some code for a 

```
export default class PaymentMeanBrand {
  static AMEX = 'AMEX';
  static BCMC = 'BCMC';
  static CBCONLINE = 'CBCONLINE';
  static ELV = 'ELV';
  static IDEAL = 'IDEAL';
  static IGNHOMEPAY = 'IGNHOMEPAY';
  static KBCONLINE = 'KBCONLINE';
  static MAESTRO = 'MAESTRO';
  static MASTERCARD = 'MASTERCARD';
  static MASTERPASS = 'MASTERPASS';
  static PAYPAL = 'PAYPAL';
  static PAYTRAIL = 'PAYTRAIL';
  static SOFORTUBERWEISUNG = 'SOFORTUBERWEISUNG';
  static VISA = 'VISA';
  static VPAY = 'VPAY';
}
```

As we checked out the PaymentRequest Class code we tried to use: paymentMeanBrandList:
`paymentRequest.paymentMeanBrandList = PaymentMeanBrand.BCMC;`

Which gives us a similar error as previous post:
`errorFieldName: paymentMeanBrandList`

Could you point me to the right direction for defining the paymentMean(Brand)(List)?

Thanks in advance!

**Comment by CrlH** [comment]
@mathieumagalhaes That should be an array, even if there's only one _paymentMeanBrand_ specified.
I got a successful response by using:

```javascript
const paypageClient = new PaypageClient(
  Environment.SIMU,
  '002001000000001',
  1,
  '002001000000001_KEY1',
);

paymentRequest.amount = 1;
paymentRequest.currencyCode = Currency.EUR;
paymentRequest.orderChannel = OrderChannel.INTERNET;
paymentRequest.paymentMeanBrandList = [PaymentMeanBrand.VISA];
paymentRequest.normalReturnUrl = 'http://localhost:3000';
paymentRequest.transactionReference = 'refdev' + new Date().getTime();
```
**Edits explained**
- Using `002001000000001` and `002001000000001_KEY1`. The one used in the documentation does not require `transactionReference`, which is not the default setting. Docs will be updated.
- Using `PaymentMeanBrand.VISA` because Bancontact is not available in SIMU
- Added mandatory `normalReturnUrl``
- Updated `transactionReference`, because of size limit (35) and invalid char (should be alphanumeric)

Working on a new, cleaned up release at the moment, should be published later today.

**Comment by mathieumagalhaes** [comment]
@CrlH Bancontact is not available in Simulation that clears up a lot.
Thank you for your outstanding explanation!
